export const constants = {
    CITIES_ENDPOINT: "/api/cities",
    DISTRICTS_ENDPOINT: "/api/districts",
    PHARMACIES_ENDPOINT: "/api/pharmacies",

    SELECTED_CITY_KEY:  "NOBETCI_ECZANELER_NCZ_SELECTED_CITY",
    SELECTED_DISTRICT_KEY:  "NOBETCI_ECZANELER_NCZ_SELECTED_DISTRICT",
}