export enum StorageKeys {
    SELECTED_CITY_KEY =  "NOBETCI_ECZANELER_NCZ_SELECTED_CITY",
    SELECTED_DISTRICT_KEY =  "NOBETCI_ECZANELER_NCZ_SELECTED_DISTRICT",
    LAST_TEN_CITY_DISTRICT =  "NOBETCI_ECZANELER_NCZ_LAST_TEN_CITY_DISTRICT",
    TODAYS_PHARMACIES =  "NOBETCI_ECZANELER_NCZ_TODAYS_PHARMACIES",
}
